/* Adapted from v7 sys.s with hacks for know deviation in Venix */
#define TARGET_VENIX_NR_indir	0
#define TARGET_VENIX_NR_exit	1
#define TARGET_VENIX_NR_fork	2
#define TARGET_VENIX_NR_read	3
#define TARGET_VENIX_NR_write	4
#define TARGET_VENIX_NR_open	5
#define TARGET_VENIX_NR_close	6
#define TARGET_VENIX_NR_wait	7
#define TARGET_VENIX_NR_creat	8
#define TARGET_VENIX_NR_link	9
#define TARGET_VENIX_NR_unlink	10
#define TARGET_VENIX_NR_exec	11
#define TARGET_VENIX_NR_chdir	12
#define TARGET_VENIX_NR_time	13
#define TARGET_VENIX_NR_mknod	14
#define TARGET_VENIX_NR_chmod	15
#define TARGET_VENIX_NR_chown	16
#define TARGET_VENIX_NR_break	17
#define TARGET_VENIX_NR_stat	18
#define TARGET_VENIX_NR_lseek	19
#define TARGET_VENIX_NR_getpid	20
#define TARGET_VENIX_NR_mount	21
#define TARGET_VENIX_NR_umount	22
#define TARGET_VENIX_NR_setuid	23
#define TARGET_VENIX_NR_getuid	24
#define TARGET_VENIX_NR_stime	25
#define TARGET_VENIX_NR_ptrace	26
#define TARGET_VENIX_NR_alarm	27
#define TARGET_VENIX_NR_fstat	28
#define TARGET_VENIX_NR_pause	29
#define TARGET_VENIX_NR_utime	30
#define TARGET_VENIX_NR_smdate	30
#define TARGET_VENIX_NR_stty	31
#define TARGET_VENIX_NR_gtty	32
#define TARGET_VENIX_NR_access	33
#define TARGET_VENIX_NR_nice	34
#define TARGET_VENIX_NR_sleep	35
#define TARGET_VENIX_NR_sync	36
#define TARGET_VENIX_NR_kill	37
#define TARGET_VENIX_NR_csw	38
#define TARGET_VENIX_NR_setpgrp	39
#define TARGET_VENIX_NR_dup	41
#define TARGET_VENIX_NR_pipe	42
#define TARGET_VENIX_NR_times	43
#define TARGET_VENIX_NR_profil	44
#define TARGET_VENIX_NR_setgid	46
#define TARGET_VENIX_NR_getgid	47
#define TARGET_VENIX_NR_signal	48
#define TARGET_VENIX_NR_acct	51
#define TARGET_VENIX_NR_phys	52
#define TARGET_VENIX_NR_lock	53
#define TARGET_VENIX_NR_ioctl	54
#define TARGET_VENIX_NR_reboot	55
#define TARGET_VENIX_NR_chroot	56
#define TARGET_VENIX_NR_setinf	59
#define TARGET_VENIX_NR_umask	60
#define TARGET_VENIX_NR_getinf	60

